services:
  - type: web
    name: farmanatura-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: farmanatura-db
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true